### ISSUE TITLE
Seeing double🤣

### ISSUE THREAD

**Issue by LuukBotter** [rahulmalhotra/Platform-Event-Toast-LWC#3]
Hi Rahul Malhotra, 

I've added this component to my dev organization but i got a little problem😁

I've created a flow that launched your tool and it worked quiet easy. But when i had 2 different leads next to each other and i activated it on the trigger sub status to "price indication" i saw the warning on both lead record. Now is that not a big problem when your working on your own. But happens this also when multiple people are working on leads on different computers and that they get the notification in their screen even when they don't trigger the flow? 

I'm looking forward to your respons! 😂

Thanks in advance! 

See the video attached for an extra explanation

https://user-images.githubusercontent.com/93350941/139332624-aaa21c5a-99c3-49ec-99b1-3250ecaccee0.mp4

**Comment by rahulmalhotra** [comment]
Hi @LuukBotter thank you for reporting this. 

In the latest release v1.1 of  Platform Event Toast, a check for record id is also added so that the toast is only visible to a single record page if multiple record pages of same object are opened in different tabs (like in your video). You need to pass the record id to use this feature while creating the toast event record and you should not receive this error. Also, please make sure that you're running the toast in user context and not in system context so that it's only available to the user working on the lead.

Hope that helps!

**Comment by rahulmalhotra** [comment]
Closing this issue as it's been over 30 days without any activity.
